name: minimal_notes_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  google_fonts: ^8.0.2
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  fpdart: ^1.1.0
  forui: ^0.22.3
  equatable: ^2.0.7
  flutter_slidable: ^4.0.3
  flutter_lucide: ^1.11.0
  flutter_quill: ^11.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true
 